/* /////////////////////////////////////////////////////////////////////////////////////////////////
//
//  IMPORTANT: READ BEFORE DOWNLOADING, COPYING, INSTALLING OR USING.
//
//  By downloading, copying, installing or using the software you agree to this license.
//  If you do not agree to this license, do not download, install,
//  copy or use the software.
//
//                                 MIT License
//                            Copyright (c) 2019 VIA, Inc.
//
// Permission is hereby granted, free of charge, to any person obtaining a copy of this software
// and associated documentation files (the "Software"), to deal in the Software without restriction,
// including without limitation the rights to use, copy, modify, merge, publish, distribute,
// sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all copies or
// substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT
// NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
// NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
// DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
//
//
// ////////////////////////////////////////////////////////////////////////////////////////////// */

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_via_adas_automotive_AutomotiveController */

#ifndef _Included_com_via_adas_automotive_AutomotiveController
#define _Included_com_via_adas_automotive_AutomotiveController
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_via_adas_automotive_AutomotiveController
 * Method:    jni_create
 * Signature: (ILjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_viatech_automotive_AutomotiveController_jni_1create
  (JNIEnv *, jobject, jint, jstring, jstring, jfloat, jfloat);

/*
 * Class:     com_via_adas_automotive_AutomotiveController
 * Method:    jni_release
 * Signature: (J)J
 */
JNIEXPORT void JNICALL Java_com_viatech_automotive_AutomotiveController_jni_1release
        (JNIEnv *, jobject, jlong);


/*
 * Class:     com_via_adas_automotive_AutomotiveController
 * Method:    jni_stopRecord
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_viatech_automotive_AutomotiveController_jni_1stopRecord
        (JNIEnv *, jobject, jlong);

/*
 * Class:     com_via_adas_automotive_AutomotiveController
 * Method:    jni_startRecord
 * Signature: (JLjava/lang/String;Z)Z
 */
JNIEXPORT jboolean JNICALL Java_com_viatech_automotive_AutomotiveController_jni_1startRecord
        (JNIEnv *, jobject, jlong, jstring, jboolean);


/*
 * Class:     com_via_adas_automotive_AutomotiveController
 * Method:    jni_runAutoControl
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_viatech_automotive_AutomotiveController_jni_1runAutoControl__J
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_via_adas_automotive_AutomotiveController
 * Method:    jni_registerCANbusModule
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_com_viatech_automotive_AutomotiveController_jni_1registerCANbusModule
  (JNIEnv *, jobject, jlong, jlong);


/*
 * Class:     com_via_adas_automotive_AutomotiveController
 * Method:    jni_registerCameraModule
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_com_viatech_automotive_AutomotiveController_jni_1registerCameraModule
        (JNIEnv *, jobject, jlong, jlong);


/*
 * Class:     com_via_adas_automotive_AutomotiveController
 * Method:    jni_registerSensingModule_Lane
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_com_viatech_automotive_AutomotiveController_jni_1registerSensingModule_1Lane
  (JNIEnv *, jobject, jlong, jlong);

/*
 * Class:     com_via_adas_automotive_AutomotiveController
 * Method:    jni_registerSensingModule_ForwardVehicle
 * Signature: (JJ)Z
 */
JNIEXPORT jboolean JNICALL Java_com_viatech_automotive_AutomotiveController_jni_1registerSensingModule_1ForwardVehicle
  (JNIEnv *, jobject, jlong, jlong);


/*
 * Class:     com_via_adas_automotive_AutomotiveController
 * Method:    jni_updateLatitudePlan
 * Signature: (J[F[F)Z
 */
JNIEXPORT jboolean JNICALL Java_com_viatech_automotive_AutomotiveController_jni_1updateLatitudePlanTrajectory
        (JNIEnv *, jobject, jlong, jfloatArray, jfloatArray);

/*
 * Class:     com_via_adas_automotive_AutomotiveController
 * Method:    jni_updateLatitudePlanLaneData
 * Signature: (J[F[F[F)Z
 */
JNIEXPORT jboolean JNICALL Java_com_viatech_automotive_AutomotiveController_jni_1updateLatitudePlanLaneData
        (JNIEnv *, jobject, jlong, jfloatArray, jfloatArray, jfloatArray);

/*
 * Class:     com_via_adas_automotive_AutomotiveController
 * Method:    jni_enableCameraCalibration
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_com_viatech_automotive_AutomotiveController_jni_1runCameraCalibration
        (JNIEnv *, jobject, jlong, jint, jfloat, jfloat);

/*
 * Class:     com_via_adas_automotive_AutomotiveController
 * Method:    jni_setCtl_SteeringControl
 * Signature: (JZJ)V
 */
JNIEXPORT void JNICALL Java_com_viatech_automotive_AutomotiveController_jni_1setCtl_1SteeringControl
        (JNIEnv *, jobject, jlong, jboolean, jlong);

#ifdef __cplusplus
}
#endif
#endif
