/* /////////////////////////////////////////////////////////////////////////////////////////////////
//
//  IMPORTANT: READ BEFORE DOWNLOADING, COPYING, INSTALLING OR USING.
//
//  By downloading, copying, installing or using the software you agree to this license.
//  If you do not agree to this license, do not download, install,
//  copy or use the software.
//
//                                 MIT License
//                            Copyright (c) 2019 VIA, Inc.
//
// Permission is hereby granted, free of charge, to any person obtaining a copy of this software
// and associated documentation files (the "Software"), to deal in the Software without restriction,
// including without limitation the rights to use, copy, modify, merge, publish, distribute,
// sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all copies or
// substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT
// NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
// NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
// DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
//
//
// ////////////////////////////////////////////////////////////////////////////////////////////// */

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_via_adas_car_CANbusModule */

#ifndef _Included_com_via_adas_car_CANbusModule
#define _Included_com_via_adas_car_CANbusModule
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     com_via_adas_car_CANbusModule
 * Method:    jni_getModuleNativeAddress
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_com_viatech_vBus_CANbusModule_jni_1getModuleNativeAddress
        (JNIEnv *, jobject, jlong);

/*
 * Class:     com_via_adas_car_CANbusModule
 * Method:    jni_init
 * Signature: (II)J
 */
JNIEXPORT jlong JNICALL Java_com_viatech_vBus_CANbusModule_jni_1init
        (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_via_adas_car_CANbusModule
 * Method:    jni_release
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_viatech_vBus_CANbusModule_jni_1release
        (JNIEnv *, jobject, jlong);

/*
 * Class:     com_via_adas_car_CANbusModule
 * Method:    jni_exec
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_viatech_vBus_CANbusModule_jni_1exec
        (JNIEnv *, jobject, jlong);

/*
 * Class:     com_via_adas_car_CANbusModule
 * Method:    jni_isConnected
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_viatech_vBus_CANbusModule_jni_1isConnected
        (JNIEnv *, jobject, jlong);

/*
 * Class:     com_via_adas_car_CANbusModule
 * Method:    jni_connect
 * Signature: (JI)Z
 */
JNIEXPORT jboolean JNICALL Java_com_viatech_vBus_CANbusModule_jni_1connect
        (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_via_adas_car_CANbusModule
 * Method:    jni_refresh
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_viatech_vBus_CANbusModule_jni_1refresh
        (JNIEnv *, jobject, jlong);


/*
 * Class:     com_via_adas_car_CANbusModule
 * Method:    jni_stopRecord
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_viatech_vBus_CANbusModule_jni_1stopRecord
        (JNIEnv *, jobject, jlong);

/*
 * Class:     com_via_adas_car_CANbusModule
 * Method:    jni_startRecord
 * Signature: (JLjava/lang/String;Z)Z
 */
JNIEXPORT jboolean JNICALL Java_com_viatech_vBus_CANbusModule_jni_1startRecord
        (JNIEnv *, jobject, jlong, jstring, jboolean);


/*
 * Class:     com_via_adas_car_CANbusModule
 * Method:    jni_setGPS
 * Signature: (JDD)V
 */
JNIEXPORT void JNICALL Java_com_viatech_vBus_CANbusModule_jni_1setGPS
        (JNIEnv *, jobject, jlong, jdouble, jdouble);

/*
 * Class:     com_via_adas_car_CANbusModule
 * Method:    jni_setCANData_CANHealth
 * Signature: (ZZ)V
 */
JNIEXPORT void JNICALL Java_com_viatech_vBus_CANbusModule_jni_1manualCANData_1CANHealth
        (JNIEnv *, jobject, jlong, jboolean, jboolean);

/*
 * Class:     com_via_adas_car_CANbusModule
 * Method:    jni_setCANdata_Speed
 * Signature: (FFFFFF)V
 */
JNIEXPORT void JNICALL Java_com_viatech_vBus_CANbusModule_jni_1manualCANdata_1Speed
        (JNIEnv *, jobject, jlong, jfloat, jfloat, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     com_via_adas_car_CANbusModule
 * Method:    jni_setCANdata_SteeringSensor
 * Signature: (FFBZ)V
 */
JNIEXPORT void JNICALL Java_com_viatech_vBus_CANbusModule_jni_1manualCANdata_1SteeringSensor
        (JNIEnv *, jobject, jlong, jfloat, jfloat, jbyte, jboolean);

/*
 * Class:     com_via_adas_car_CANbusModule
 * Method:    jni_setCANdata_DriverControllers
 * Signature: (ZZB)V
 */
JNIEXPORT void JNICALL Java_com_viatech_vBus_CANbusModule_jni_1manualCANdata_1DriverControllers
        (JNIEnv *, jobject, jlong, jboolean, jboolean, jbyte);

#ifdef __cplusplus
}
#endif
#endif
